// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	MCountry         string
	TCompany         string
	TUser            string
	TUserWorkHistory string
}{
	MCountry:         "m_country",
	TCompany:         "t_company",
	TUser:            "t_user",
	TUserWorkHistory: "t_user_work_history",
}
